[server]
# Конфигурация для Streamlit Cloud v1.2
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
# Настройки браузера для улучшенного UX
gatherUsageStats = false
showErrorDetails = true

[theme]
# Тема интерфейса
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[global]
# Глобальные настройки приложения v1.2
developmentMode = false
logLevel = "info"

# Force rebuild timestamp: 2025-08-04-02:50 - Fixed backend requirements